name = "lide"
main = "src/index.js"
compatibility_date = "2023-05-18"

[observability.logs]
enabled = false

[vars]
DEFAULT_URL = "https://ys.jiedianxielou.workers.dev,https://gist.githubusercontent.com/byrisk/172280d15a99a420c2ec0d190be8e40a/raw/all.yaml,https://gist.githubusercontent.com/byrisk/904fcf74c6299b728fb2b83d621832dd/raw/MQconfig.yaml,https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash,https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml,https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml,https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml,https://raw.githubusercontent.com/chengaopan/AutoMergePublicNodes/master/list.yml,https://raw.githubusercontent.com/go4sharing/sub/main/sub.yaml,https://raw.githubusercontent.com/qjlxg/aggregator/main/data/clash.yaml"
[build]
command = "npm install"
